title: "Faces of Fieldwork"
description: "Scientists are people too. We show the personal side of scientific fieldwork."
about: "Scientists are people too. We show the personal side of scientific fieldwork."
location: "All around the world"
email: "fof.contribute@gmail.com"
contributeURL: "/upload_image/"
default_share_image: "https://i.imgur.com/QvWmwbK.jpg"
twitter_card_image: "https://i.imgur.com/QvWmwbK.jpg"
baseurl: ""
FacebookAppID: 1616633811967151
url: "http://facesoffieldwork.com" # replace by your site's url
twitter_username: facesfieldwork
permalink: /:title/
gems: [jekyll-paginate, jekyll-redirect-from]
paginate: 5

youtubeparams: "?rel=0&controls=1&showinfo=0&modestbranding=1"

# google analytics tracking code, please change the value
g_analytics: "UA-85189653-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md