title: "Faces of Fieldwork"
description: "Putting a human face on scientific fieldwork"
about: "Putting a human face on scientific fieldwork"
location: "All around the world"
email: "fof.contribute@gmail.com"
contributeURL: "/upload_image/"
default_share_image: "http://i.imgur.com/rQ3Qjo9.jpg"
twitter_card_image: "http://i.imgur.com/fPzrPQxl.jpg"
baseurl: ""
FacebookAppID: 1616633811967151
url: "http://facesoffieldwork.com" # replace by your site's url
twitter_username: facesfieldwork
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# google analytics tracking code, please change the value
g_analytics: "UA-85189653-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md